version: "3.4"

services:
  update-workout-data:
    image: custom-suunto-app
    container_name: custom-suunto-app_update-workout-data
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ../backend/data:/app/data
    working_dir: /app/
    env_file: .env.updateWorkoutData
    command: "node build/updateWorkoutData.js ${API_TOKEN}"
