version: "3.4"

services:
  webapp:
    image: custom-suunto-app
    container_name: custom-suunto-app_webapp
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - ../backend/data:/app/data
      - ../backend/cache:/app/cache
    working_dir: /app/
    ports:
      - 4000:4000

    command: node build/index.js
