version: "3.4"

services:
  update-workout-data:
    image: workout-tracker
    container_name: workout-tracker_update-workout-data
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ../backend/data:/app/data
    working_dir: /app/
    env_file: .env.updateWorkoutData
    command: "node build/updateWorkoutData.js ${API_TOKEN}"
