apiVersion: v1
kind: Namespace
metadata:
  name: workout-tracker

---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-environment-secret
  namespace: workout-tracker
type: Opaque
stringData:
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  AUTH0_DOMAIN: ""
  AUTH0_CLIENT_ID: ""
  AUTH0_CLIENT_SECRET: ""
  DB_USER: admin
  DB_PASSWORD: change-me
  DB_NAME: workout-tracker
  DB_HOST: mongodb:27017

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-environment-config
  namespace: workout-tracker
data:
  PUBLIC_URL: https://workout.silte.fi
  COOKIE_KEY: workout-tracker-production
  SUUNTO_DATA_DIR: /app/data/
  FETCH_WORKOUT_CHUNK_SIZE: "5"
  BUILD_WORKOUT_CACHE_CHUNK_SIZE: "50"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-crentials-secret
  namespace: workout-tracker
type: Opaque
stringData:
  MONGO_INITDB_DATABASE: workout-tracker
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: change-me
